config/routes.rb
Oddjobs::Application.routes.draw do
  get "pages/home"

  devise_for :jobseekers, :controllers => {:registrations => "registrations"}
  resources :oddjobs 
  # Sample of regular route:
   
  root :to => 'pages#index'
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/jobseeker.rb
class Jobseeker < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :phone_number, :verified
  validates :phone_number, presence: true
  # attr_accessible :title, :body
end

app/models/oddjob.rb
class Oddjob < ActiveRecord::Base
  attr_accessible :company, :date_posted, :description, :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/oddjobs_controller.rb
class OddjobsController < ApplicationController
  def index
    @oddjobs = Oddjob.all

    respond_to do |format|
       format.html 
       format.json { render :json => @oddjobs }
    end
  end

  def new
    @oddjob = Oddjob.new
  end
  
  def create
    @oddjob = Oddjob.new(params[:oddjob])

    respond_to do |format|
      if @oddjob.save
         format.html { redirect_to(@oddjob,
                       :notice => 'post was successfully created.') }
         format.json { render :json => @oddjob,
                       :status => :created, :location => @post }
      else
         format.html { render :action => 'new' }
         format.json { render :json => @oddjob.errors,
                       :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @oddjob = Oddjob.find(params[:id])
    
    respond_to do |format|
    format.html 
    format.json { render :json => @oddjob }
     end
  end
 
 def edit
    @oddjob = Oddjob.find(params[:id])
 end
 
 def update
    @oddjob = Oddjob.find(params[:id])
    
    respond_to do |format|
       if @oddjob.update_attributes(params[:id])
          format.html { redirect_to(@oddjob,
                        :notice => 'Post was successfully updated.') }
          format.json { head :no_content }
       else
          format.html { render :action => 'edit' }
          format.json { render :json => @oddjob.errors,
                        :status => :unprocessable_entity }
       end
    end
 end
 
 def destroy

   @oddjob = Oddjob.find(params[:id])
   @oddjob.destroy

   respond_to do |format|
     format.html { redirect_to oddjobs_url }
     format.json { head :no_content }
   end
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    build_resource

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
        # Instantiate a Twilio client
      client = Twilio::REST::Client.new(TWILIO_CONFIG['sid'], TWILIO_CONFIG['token'])
      
      # Create and send an SMS message
      client.account.sms.messages.create(
        from: TWILIO_CONFIG['from'],
        to: resource.phone_number,
        body: "Thanks for signing up. To verify your account, please reply HELLO to this message."
      )
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

protected

  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oddjobs_helper.rb
module OddjobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobseekers/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Oddjobs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <%= render "partials/nav" %>
    <div class="container-fluid">
      <div class="row-fluid">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/oddjobs/_form.html.erb
<%= form_for(@oddjob) do |f| %>

  <div class="field">
   <%= f.label :job %>
   <%= f.text_field :job %>
  </div>
 
  
  <div class="field">
   <%= f.label :company %>
   <%= f.text_field :company %>
  </div>

  
  <div class="field">
   <%= f.label :description %>
   <%= f.text_field :description %>
  </div>
<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oddjobs/edit.html.erb
<h1>Editing Posts</h1>

<%= render 'form' %>

<% link_to 'show', @oddjob %>
<% link_to 'Back', oddjob_path(@oddjob) %>

app/views/oddjobs/index.html.erb
<h1>Listing oddjobs</h1>
 
<table>
  <tr>
    <th>Job</th>
    <th>Company</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @oddjobs.each do |oddjob| %>
  <tr>
    <td><%= oddjob.job %></td>
    <td><%= oddjob.company %></td>
    <td><%= oddjob.description %></td>
    <td><%= link_to 'Show', oddjob %></td>
    <td><%= link_to 'Edit', edit_oddjob_path(oddjob) %></td>
    <td><%= link_to 'Destroy', oddjob, :confirm => 'Are you sure?',
                                     :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New oddjob', new_oddjob_path %>

app/views/oddjobs/new.html.erb
<h1>New Oddjob</h1>

<%= render 'form' %>
<%= link_to 'Back', oddjobs_path %>
<%= link_to 'Show', @oddjob %>

app/views/oddjobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @oddjob.company %>
</p>

<p>
  <b>Job:</b>
  <%= @oddjob.job %>
</p>


<%= link_to 'Edit', edit_oddjob_path(@oddjob) %>

app/views/pages/index.html.erb
<div class="center hero-unit">
  <h1>Odd Jobs</h1>
  
  <h2>
   Are you looking for on call or part-time job.?
  </h2>

<%= link_to "Sign Up Here!", "jobseekers/sign_up/", :class => "btn btn-large btn-primary" %>
</div>

app/views/partials/_nav.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Oddjobs</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
             <% if jobseeker_signed_in? %>
             <li><%= link_to "Home", root_path %></li>
             <li> <%= link_to "Sign out", destroy_jobseeker_session_path, :method => :delete %></li>
             <% else %>
             <li><%= link_to "Home", root_path %></li>
             <li><%= link_to "Sign in", new_jobseeker_session_path %>
             <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/partials/nav.html.erb
<div class="container-fluid nav-collapse">
              <ul class="nav">
             <% if jobseeker_signed_in? %>
             <li><%= link_to "Home", root_path %></li>
           <li> <%= link_to "Sign out", destroy_jobseeker_session_path, :method => :delete %></li>
            <% else %>
             <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Sign in", new_jobseeker_session_path %>
            <% end %>
             </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>